### ISSUE TITLE
Garbled text issues with CSV files when opening in Excel

### ISSUE THREAD

**Issue by KC-Lan** [ChenHsieh/MMP_screening#2]
Change the encoding from 'utf-8' to 'utf-8-sig' to prevent garbled text issues when opening CSV files in Excel.

Update [app_screening.py](https://app_screening.py/): Line 51

```python
def convert_df(df):
    # IMPORTANT: Cache the conversion to prevent computation on every rerun
    return df.to_csv().encode('utf-8')
```

```python
def convert_df(df):
    # IMPORTANT: Cache the conversion to prevent computation on every rerun
    return df.to_csv().encode('utf-8-sig')
```

**Comment by ChenHsieh** [comment]
Thank you for your suggestion to change the encoding from 'utf-8' to 'utf-8-sig' to prevent garbled text issues when opening CSV files in Excel. I've implemented the change in both `app_screening.py` and `app_matching_confirmation.py`. 

I apologize for overlooking the pull request you previously submitted. I have been quite busy and missed reviewing it in a timely manner. I appreciate your contribution and patience. If there are any additional improvements or suggestions, please don't hesitate to share them. Thank you!

**Comment by KC-Lan** [comment]
Thank you for your prompt reply and all your efforts regarding the Mentor-Mentee Program of Project Tyra. 😃
